version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__connnectionURI=mongodb://mongo:27017/
      - MongoDB__DatabaseName=Feedback_1305
      - MongoDB__CollectionName=kundenFeedback
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

networks:
  default:
    name: mynetwork
